baseURL = "https://blog.sneakybugs.com"
title = "Sneaky Bugs"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "sneakybugs"
taxonomies = []
disableKinds = ["section"]
pygmentsUseClasses = true

[menu]
[[menu.footer]]
  name = "GitHub"
  url = "https://github.com/LKummer"
[[menu.footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/lior-friedman-b0509b2aa/"

[params]
[params.author]
  name = "Lior Friedman"
  url = "https://sneakybugs.com"
[params.seo]
  description = "Tech blog focusing on web development. Covers everything from frontend, to backend, to infrastructure."
  twitterCard = "summary_large_image"
[params.seo.images]
  ogPath = "images/1x1.png"
  ldPaths = [
    "images/1x1.png",
    "images/4x3.png",
    "images/16x9.png"
  ]
[params.footer]
  aboutTitle = "What's with the hedgehog?"
  aboutText = "I am Lior, since I remember myself I had a passion for making stuff. I take interest in anything that can improve my projects; from frontend, to backend, to infrastructure technologies."
  aboutExtra = "This website values your privacy and does not use invasive analytics."
  menuTitle = "More from me"
